repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c" # pinned to v6.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/specklesystems/pre-commit
    rev: "e4bde6ce7cab76bfbf1b8fecc226e54e272513c0" # pinned to 0.3.0
    hooks:
      - id: ggshield-not-ci
        name: ggshield

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: "9257c6050c0261b8c57e712f632dc4a8010109a9" # pinned to 1.25.2
    hooks:
      - id: zizmor
        name: GitHub Actions linter
        language_version: python3
        args:
          - --persona=auditor
