name: 'Speckle Automate Function - Build and Publish'
description: 'Builds and publishes a new version of a Speckle Automate Function to the Speckle Automate platform.'
author: 'specklesystems'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  speckle_automate_url:
    description: 'Speckle Automate URL. Should include the `https://` protocol and not end with a trailing slash.'
    required: false
    default: 'https://automate.speckle.dev' #TODO change to https://automate.speckle.systems
  speckle_token:
    description: 'Token for authentication to Speckle Automate Server, allowing publishing of Speckle Functions. **The token must be stored in GitHub as an encrypted secret**.'
    required: true
  speckle_function_id:
    description: 'The unique identifier of the function. Go to Speckle Automate to register your Function and get its Identifier.'
    required: true
  speckle_function_input_schema_file_path:
    description: 'File path containing JSON Schema of the parameters object required by the function. These will be used to create the User Interface displayed to users of your Function in Speckle Automate. Users will be able to provide their data to customise the Function.'
    required: false
  speckle_function_command:
    description: 'The command to run to execute the function in a runtime environment.'
    required: true
  dockerfile_path:
    description: 'Path to the Dockerfile to be used to build the Speckle Function.'
    required: false
    default: './Dockerfile'
  docker_context:
    description: 'Path to the directory containing the build context for the Docker image.'
    required: false
    default: '.' # root directory of the checked out source code
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3.5.3 # checkout the repository in which this GitHub Action is being used.
      - name: Set Version tag
        shell: bash
        run: |
          echo "Determining Release tag value"

          if [[ ${GITHUB_REF_TYPE} == "tag" ]]
          then
            echo "Workflow triggered by a git tag"
            RELEASE_TAG=${GITHUB_REF_NAME}
          else
            echo "Workflow triggered on a git branch"
            RELEASE_TAG=$(git rev-parse --short ${GITHUB_SHA})
          fi

          echo "Setting the function's releaseTag to: ${RELEASE_TAG}"
          echo "releaseTag=${RELEASE_TAG}" >> "$GITHUB_ENV"
      - name: Log in to Speckle Automate Docker registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ inputs.speckle_automate_url }}
          username: ${{ inputs.speckle_token }}
          password: ${{ inputs.speckle_token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.dockerfile_path }}
          tags: ${{ steps.register_speckle_function_version.outputs.speckle_automate_host }}/${{ inputs.speckle_function_id }}:${{ env.releaseTag }}
          target: ''
          push: true
      - name: Speckle Automate function version publisher
        uses: specklesystems/speckle-automate-github-action@0.6.0
        id: register_speckle_function_version
        with:
          speckle_automate_url: ${{ inputs.speckle_automate_url }}
          speckle_token: ${{ inputs.speckle_token }}
          speckle_function_id: ${{ inputs.speckle_function_id }}
          speckle_function_input_schema_file_path: ${{ inputs.speckle_function_input_schema_file_path }}
          speckle_function_release_tag: ${{ env.releaseTag }}
          speckle_function_command: ${{ inputs.speckle_function_command }}
